### ISSUE TITLE
Is that lib reliable and up to date ?

### ISSUE THREAD

**Issue by cyrilchapon** [alma/alma-js-client#1]
We're about to integrate Alma.

Is that lib ready to use, or is that preferable to go for REST API ?

**Comment by olance** [comment]
@cyrilchapon so sorry for missing your question, looks I've been having some notifications issues on several of our repos :\

In any case, this lib wasn't ready at that time and still isn't for a proper Alma integration, for a lack of projects requiring such a lib.

We'll be getting there soon, though!

**Comment by cyrilchapon** [comment]
@olance in the meantime; check what we've done here https://github.com/permettez-moi-de-construire/alma-client

Used in production

**Comment by olance** [comment]
Ah, thanks for the link!

And nice job on the lib too :)
I remember now that you had been in contact with our sales or support about it, am I right?

From the source I can see you've had some interrogations on the API data shape (which might not always be consistent depending on the endpoint being used 😓 )... feel free to ping me on specific points if you want to strengthen your typings!

**Comment by cyrilchapon** [comment]
@olance yeah right.

I'm not in there anymore, but I'm still contributor on this.
I'd love use Alma back in the future, this is an awesome product.

I'd recommend you creating a record for Alma in https://stackshare.io/ so we can spread the word ;)

**Comment by olance** [comment]
Thanks for the kind words 😊 
And glad you like what we're doing!

Good point for StackShare, I'll look into it :)
